### PR TITLE
About type

### PR DESCRIPTION
**Pull request by tssailzz8**
i think we can  use attribute  rather than use that method

### CODE REVIEW

**Comment by marzent** [comment]
Indeed this is such faster and we don't need to use reflection here...

Would you mind changing `GetPartyType` itself, since it is being used multiple times?

**Comment by tssailzz8** [comment]
in face,i want to use dalamud data

**Comment by marzent** [comment]
Indeed that would be nice long term

**Comment by marzent** [comment]
Thanks for this; I have implemented this fix in GetPartyType already with https://github.com/marzent/IINACT/commit/79a26cdd4c73aad7f4e051786d15bc7ef17ecdc5 so will be closing this

**Pull request closed without merging**
