### PR TITLE
Patch and use the Machina library bundled in FFXIV_ACT_Plugin 

### PR DESCRIPTION
**Pull request by Menci**
Currently IINACT use an owned fork of the Machina library. While Machina.FFXIV contains the game client's opcode, the fork needs to be updated for each game version. If we want to also [support the Chinese client](https://github.com/marzent/machina/compare/52f4d1e1349e6d35aa6964859c61de429e6d4df7...712b147e1e50f0743603c90fd8cc4bfea42b0e69#diff-aeb08e6be015ad36af82926046e8d6803056135dab3f37032c957708c09586b9), things become harder since the open-source repo of Machina [doesn't even contain](https://github.com/ravahn/machina/pull/33) the latest opcodes for Chinese client.

Since we're only replacing the `DeucalionClient` with `DalamudClient` in the Machina library, we can do it dynamically for the Machina library bundled in FFXIV_ACT_Plugin, then we won't need to maintain the opcodes manually anymore.

### CODE REVIEW

**Comment by marzent** [comment]
Sorry for not coming back to you earlier!

Indeed the only real problem with https://github.com/marzent/IINACT/pull/76 is that it does not point to the custom Machina submodule anymore.

In the past IINACT used to actually just use the bundled Machina, the two main reasons why I moved away from doing this was to easily implemented the Dalamud client (which you have already taken efforts to not be needed anymore) and to update the opcodes myself on patchday (ideally before the servers are already up), since I don not like to wait for the full release of the FFXIV_ACT_Plugin and then people want to use the beta, which is only available on Discord etc and it is just a headache and for me worth manually updating for.

I also wouldn't mind keeping the Chinese opcodes of the Machina fork updated in a timely manner, or maybe even some sort of CI propagation from an opcode repo.

**Comment by Menci** [comment]
Oh I even didn't know there's a Discord community! For the Chinese our maintainers usually just update the plugin on patch day since the parsing code is just from an older version of the global one and they only need the opcodes on the patch day...

How about dynamically update opcodes with an URL, just like updating the plugin zip?

**Comment by marzent** [comment]
> How about dynamically update opcodes with an URL, just like updating the plugin zip?

That would probably be ideal, but would require a bit of new infrastructure and then patch machina as well with the new opcodes...

There is also the risk of some random network issues, which especially when connecting to GitHub happens a lot, so these would have to be cached + versioned most likely as well.

**Comment by marzent** [comment]
This is also compounded by OverlayPlugin having its own list of opcodes that also need updating anyways on patch day

**Comment by DieMoe233** [comment]
> This is also compounded by OverlayPlugin having its own list of opcodes that also need updating anyways on patch day

https://github.com/moewcorp/FFXIVNetworkOpcodes

**Pull request closed without merging**
